import type { PortfolioWork } from "@/types/content";

export const portfolioWorks: PortfolioWork[] = [
  {
    id: "work-01",
    slug: "placeholder-fine-line",
    title: null,
    category: "fine-line",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original fine-line photograph required",
    width: 3,
    height: 4,
    year: null,
    featured: true,
    sortOrder: 1,
    published: true,
    status: "unknown",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-02",
    slug: "placeholder-botanical",
    title: null,
    category: "botanical",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original botanical photograph required",
    width: 4,
    height: 5,
    year: null,
    featured: true,
    sortOrder: 2,
    published: true,
    status: "unknown",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-03",
    slug: "placeholder-black-and-grey",
    title: null,
    category: "black-and-grey",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original black-and-grey photograph required",
    width: 1,
    height: 1,
    year: null,
    featured: true,
    sortOrder: 3,
    published: true,
    status: "unknown",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-04",
    slug: "placeholder-script",
    title: null,
    category: "script",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original script photograph required",
    width: 3,
    height: 4,
    year: null,
    featured: true,
    sortOrder: 4,
    published: true,
    status: "healed",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-05",
    slug: "placeholder-ornamental",
    title: null,
    category: "ornamental",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original ornamental photograph required",
    width: 4,
    height: 5,
    year: null,
    featured: true,
    sortOrder: 5,
    published: true,
    status: "fresh",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-06",
    slug: "placeholder-sketch",
    title: null,
    category: "sketch",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original sketch scan required",
    width: 4,
    height: 3,
    year: null,
    featured: true,
    sortOrder: 6,
    published: true,
    status: "unknown",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-07",
    slug: "placeholder-selected-07",
    title: null,
    category: "selected",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original photograph required",
    width: 3,
    height: 4,
    year: null,
    featured: false,
    sortOrder: 7,
    published: true,
    status: "fresh",
    contentFlag: "TODO_CONTENT",
  },
  {
    id: "work-08",
    slug: "placeholder-selected-08",
    title: null,
    category: "selected",
    description: null,
    imageSrc: null,
    imageAlt: "TODO_CONTENT — original photograph required",
    width: 4,
    height: 5,
    year: null,
    featured: false,
    sortOrder: 8,
    published: true,
    status: "unknown",
    contentFlag: "TODO_CONTENT",
  },
];

export function featuredWorks(limit = 8): PortfolioWork[] {
  return portfolioWorks
    .filter((work) => work.published && work.featured)
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .slice(0, limit);
}

export function publishedWorks(): PortfolioWork[] {
  return portfolioWorks
    .filter((work) => work.published)
    .sort((a, b) => a.sortOrder - b.sortOrder);
}
